### ISSUE TITLE
What are we doing and how?

### ISSUE THREAD

**Issue by edjeffreys** [SolentSoftwareEngineers2019/project-BigBreakfast#1]
We need to come up with a basic plan of what we're doing, such as: languages to use, layouts, database design, etc.

Please comment with ideas and suggestions.

**Comment by TobyDustin** [comment]
Okay so this is the basic outline for the program;
Web based application using simple HTML, JS and CSS but for data handlng we'll use PHP and MySQLI.
Also I want to investigate whether we can use AngularJS for searching and make the general layout more dynamic.
I'm not really bothered about design as if we include Bootsrap it should work on most desvices as well, il put up some wireframes for the diffrent pages.

Do you think users should follow each other straight from the start? or should we just make a General post page and try to impliment that later?

**Comment by edjeffreys** [comment]
> Do you think users should follow each other straight from the start? or should we just make a General post page and try to impliment that later?

I think as long as we get all the basics done first, then that shouldn't be hard to implement later.

**Comment by edjeffreys** [comment]
For starters I assume we have the following tasks:
1. Create layout and html for homepage.
2. Create layout and html for login/registration.
3. Design database.

**Comment by TobyDustin** [comment]
Yesh that's it, i made some crude wireframes for the diffrent pages (when i say crude i spent 1 minute on each) but it should give you some idea of the layout... basically copy twitter...

If i start on designing the database because that's the most important part of it then we can see where we stand

[mOJI.zip](https://github.com/SolentSoftwareEngineers2019/Moji/files/649060/mOJI.zip)

**Comment by TobyDustin** [comment]
## BASIC DATA STRUCTURES **to be improved
- **user database**
- id
-  firstname
- lastname
- date of birth
- username
-   ##password(hashed)
_______________________
- **post database**
- id
-  date/time
- userID
- content
- likes //possibility
_______________________
//For following database a prediction
- **following**
- id
- followerUserID
- followingUserID
however this may become inefficient over time

**Comment by ghost** [comment]
I think we should keep time stamp for each entry in the database. That will help us generate some statistics.

### Like(reaction) table
- id
- time stamp (date/time)
- postID
- userID

It will be a lot of data to store but it will allow us to do annual reviews (statistics) like Facebook does.
