### ISSUE TITLE
Right sidebar can not be animated after window resize

### ISSUE THREAD

**Issue by edjeffreys** [SolentSoftwareEngineers2019/project-BigBreakfast#15]
At the moment I have to make the right sidebar toggle it's visibility instead of animate after the screen has been resized as it no longer follows the right hand side of the window after resizing. If anyone has any ideas of how to fix it please let me know. In the meantime I will keep playing around and seeing what I can do to fix it.

**Comment by TobyDustin** [comment]
Okay, its looking good anyway on mobile and desktop. I'll take a look as well, im going to fork it when im done with the library

**Comment by edjeffreys** [comment]
Fixed.
