### ISSUE TITLE
Task: Database Structures and code design

### ISSUE THREAD

**Issue by TobyDustin** [SolentSoftwareEngineers2019/project-BigBreakfast#3]

**Comment by TobyDustin** [comment]
## BASIC DATA STRUCTURES **to be improved
- **user database**
- id
-  firstname
- lastname
- date of birth
- username
-   ##password(hashed)
_______________________
- **post database**
- id
-  date/time
- userID
- content
- likes //possibility
_______________________
//For following database a prediction
- **following**
- id
- followerUserID
- followingUserID
however this may become inefficient over time

**Comment by ghost** [comment]
### Like(reaction) table
- id
- time stamp (date/time)
- postID
- userID
