### ISSUE TITLE
So expla.in is taken.

### ISSUE THREAD

**Issue by TobyDustin** [SolentSoftwareEngineers2019/project-BigBreakfast#8]
and unless we can convince Bill Gates that one of us is his long lost son, I think that name is dead. 
https://sedo.com/search/details/?partnerid=14460&language=e&et_cid=15&et_lid=14274&domain=expla.in&et_sub=2014&origin=parking

**Comment by edjeffreys** [comment]
Matyas, you have $7500 to spare, right? 😂😂😂

**Comment by TobyDustin** [comment]
Haha we can come up with a name later 😂

**Comment by ghost** [comment]
I wish 😂

**Comment by edjeffreys** [comment]
I miss our big breakfasts 🥲
